name=input("Enter a name: ")
print(type(name))
score=int(input("Enter a number: "))
print(type(score))
department=input("Enter a department: ")
print("My name is:",name)
print("My score is:",score/10,"/10")
print("My department is:",department)
